services:
  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"

  spark:
    build: .
    container_name: spark_container
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq
<<<<<<< HEAD
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: /bin/bash -c "pip install requests pandas pika SPARQLWrapper flask && python3 /app/multiproc_download.py"
=======
    environment:
      - SPARK_MASTER_NAME=spark
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
>>>>>>> 5ca55d993dfa474262ca5e1a2fa9caefb07a6021
