services:
  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"

  python:
    image: python:3.10-slim
    container_name: python_container
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: /bin/bash -c "pip install requests pandas pika SPARQLWrapper flask && python3 /app/multiproc_download.py"
