version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bigdata-main-network

  downloader:
    build: ./downloader
    container_name: downloader_container
    command: tail -
    depends_on:
      - rabbitmq
    networks:
      - bigdata-main-network

  metadata-extractor:
    build: ./metadata_extractor
    container_name: metadata_extractor_container
    depends_on:
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bigdata-main-network

networks:
  bigdata-main-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.169.20.0/24
